version: "3"
services: 
  mongo:
    image: mongo:latest
    volumes:
      - todo-data:/data/db
    restart: on-failure

  todoapp:
    image: pavanp2/todo-node-app:latest
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    restart: on-failure
        
volumes: 
  todo-data: