version: "3"
services: 
  mongo:
    image: mongo:latest
    volume:
      todo-data: /data/db
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  todo:
    image: pavanp2/todo-node-app
    ports:
      "3000:3000"
    depends_on:
      mongo
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        
  volumes: 
    todo-data: